---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by AClockworkOrange.
--- DateTime: 12/12/2022 17:01
---

-- 当前线程的key
local key = KEYS[1]
-- 当前线程的标识
local currentInfo = ARGV[1]
-- redis中线程标识
local redisInfo = redis.call("get", key)

if redisInfo == currentInfo then
    -- 是当前线程的🔒
    return redis.call("del", key)
end
-- 删除了0个key
return 0



